name: DevOps CI - Docker + Linting

on: [push, pull_request]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Run Pylint
      run: |
        pylint app.py || true  # prevents job from failing if score < 10

    # Optional: fail if score too low
    # - name: Run Pylint with score check
    #   run: |
    #     score=$(pylint app.py | tee /dev/tty | tail -1 | awk '{print $7}')
    #     echo "Pylint Score: $score"
    #     if (( $(echo "$score < 8.0" | bc -l) )); then exit 1; fi
