name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or your working branch

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/portfolio-tracking-system:latest .

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/portfolio-tracking-system:latest
